#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: letsencrypt-prod-key
#  namespace: cert-manager
#type: Opaque
#stringData:
#  tls.key: <path:k8s/data/letsencrypt#prod>
#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: letsencrypt-staging-key
#  namespace: cert-manager
#type: Opaque
#stringData:
#  tls.key: <path:k8s/data/letsencrypt#stage>
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  tls.key: <path:k8s/data/letsencrypt#cloudflare>
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: markku@techmonkeys.se
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: letsencrypt-staging-key
    # Add a single challenge solver, DNS01
    solvers:
    - dns01:
        cloudflare:
          email: markku@techmonkeys.se
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: tls.key
      selector: {}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: markku@techmonkeys.se
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: letsencrypt-prod-key
    # Add a single challenge solver, DNS01
    solvers:
    - dns01:
        cloudflare:
          email: markku@techmonkeys.se
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: tls.key
      selector: {}