---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: controller-manager
  annotations: 
    avp.kubernetes.io/path: k8s/data/github
stringData:
  github_app_id: <github_app_id>
  github_app_installation_id: <github_app_installation_id>
  github_app_private_key: <github_app_private_key>
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: ghcr-io-secret
  annotations: 
    avp.kubernetes.io/path: k8s/data/github
data:
  .dockerconfigjson: <ghcr.io>
