---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: argocd
spec:
  parentRefs:
  - name: external-gateway
    namespace: kube-system
  hostnames:
  - argocd.maximillian.se
  rules:
  - backendRefs:
    - kind: Service
      name: argocd-server
      port: 80