---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
spec:
  destination:
    namespace: backstage
    name: in-cluster
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    - ServerSideApply=true
  source:
    repoURL: https://github.com/CloudNomster/helm-backstage
    targetRevision: main
    path: .
    helm:
      releaseName: backstage
      valueFiles:
        - values.yaml
