---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
spec:
  destination:
    namespace: backstage
    name: in-cluster
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    - ServerSideApply=true
  sources:
    - repoURL: https://github.com/CloudNomster/helm-backstage
      targetRevision: main
      path: .
      helm:
        releaseName: backstage
        valueFiles:
          - values.yaml

    - repoURL: git@github.com:CloudNomster/homelab.git
      path:  k8s/netes/overlays/backstage
      targetRevision: main