---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-config
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    name: in-cluster
  project: default
  source:
    path: k8s/netes/overlays/cluster-config
    repoURL: git@github.com:Schabo/homelab.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - PruneLast=false
      - CreateNamespace=true