---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-arc
  namespace: argocd
spec:
  destination:
    namespace: arc-systems
    name: in-cluster
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - PruneLast=false
      - CreateNamespace=true
      - ServerSideApply=true

  sources:
    - repoURL: git@github.com:CloudNomster/helm-gh-arc.git
      targetRevision: main
      path: .
      helm:
        releaseName: gh-arc
        valueFiles:
          - values.yaml

    - repoURL: git@github.com:CloudNomster/homelab.git
      path:  k8s/netes/overlays/gh-arc
      targetRevision: main


