---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vsphere-csi
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    name: in-cluster
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - PruneLast=false
      - CreateNamespace=true
      - ServerSideApply=true
    ignoreDifferences:
      - group: storage.k8s.io
        name: csi.vsphere.vmware.com
        kind: "CSIDriver"
        jsonPointers:
          - /spec/seLinuxMount

  sources:
    - repoURL: git@github.com:CloudNomster/helm-vsphere-csi.git
      targetRevision: 0.1.0
      path: .
      helm:
        releaseName: vsphere-csi
        valueFiles:
          - values.yaml

