apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
type: Opaque
stringData:
  BACKSTAGE_ORG: CloudNomster
  BACKSTAGE_TITLE: Backstage
  BACKSTAGE_BASE_URL: https://backstage.maximillian.se
  GITHUB_ORG: CloudNomster
  GITHUB_TOKEN: <path:k8s/data/github#github_token>
  ARGOCD_AUTH_TOKEN: <path:k8s/data/backstage#argocd_auth_token>
  