apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
type: Opaque
stringData:
  BACKSTAGE_ORG: CloudNomster
  BACKSTAGE_TITLE: Backstage
  BACKSTAGE_BASE_URL: https://backstage.maximillian.se
  GITHUB_ORG: CloudNomster
  GITHUB_TOKEN: <path:k8s/data/github#github_token>
  ARGOCD_URL: https://argocd.maximillian.se/api/v1/
  ARGOCD_AUTH_TOKEN: <path:k8s/data/backstage#argocd_auth_token>
  AZURE_TENANT_ID: <path:k8s/data/backstage#azure_tenant_id>
  AZURE_CLIENT_ID: <path:k8s/data/backstage#azure_client_id>
  AZURE_CLIENT_SECRET: <path:k8s/data/backstage#azure_client_secret>
  K8S_CONFIG_CA_DATA: <path:k8s/data/backstage#k8s_cadata>
