---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vsphere-cpi
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    name: in-cluster
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - PruneLast=false
      - CreateNamespace=true
      - ServerSideApply=true

  sources:
    - repoURL: git@github.com:CloudNomster/helm-vsphere-cpi.git
      targetRevision: main
      path: .
      helm:
        releaseName: vsphere-cpi
        valueFiles:
          - values.yaml
        values: |
          vsphere-cpi:
            global:
              config:
                vcenter:
                  <path:k8s/data/vsphere#hostname>:
                    server: <path:k8s/data/vsphere#hostname>
                    user: <path:k8s/data/vsphere#user>
                    password: <path:k8s/data/vsphere#pass>
                    datacenters:
                      - GeekHouse