apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: argocd-vault-plugin-credentials
  annotations: 
    avp.kubernetes.io/path: k8s/data/argocd/secrets/argocd-vault-plugin-credentials
stringData:
  VAULT_ADDR: http://central.maximillian.se:8200
  VAULT_SKIP_VERIFY: "true"
  AVP_ROLE_ID: <vaultAppRoleId>
  AVP_SECRET_ID: <vaultAppSecretId>
  AVP_TYPE: vault
  AVP_AUTH_TYPE: approle
  AVP_VAULT_SKIP_VERIFY: "true"