---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-base-repo
  annotations: 
    avp.kubernetes.io/path: k8s/data/argocd/repositories/argocd-k8s-repo
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  name: Homelab
  project: default
  type: git
  sshPrivateKey: <sshPrivateKey>
  url: git@github.com:CloudNomster/homelab.git
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-helm-dashboard
  annotations: 
    avp.kubernetes.io/path: k8s/data/argocd/repositories/argocd-k8s-repo
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  name: Helm Dashboard
  project: default
  type: git
  sshPrivateKey: <sshPrivateKey>
  url: git@github.com:CloudNomster/helm-kubernetes-dashboard.git
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-helm-gh-arc
  annotations: 
    avp.kubernetes.io/path: k8s/data/argocd/repositories/argocd-k8s-repo
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  name: Helm Github ARC
  project: default
  type: git
  sshPrivateKey: <sshPrivateKey>
  url: git@github.com:CloudNomster/helm-gh-arc.git
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-helm-vsphere-csi
  annotations: 
    avp.kubernetes.io/path: k8s/data/argocd/repositories/argocd-k8s-repo
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  name: Helm Github vSphere CSI
  project: default
  type: git
  sshPrivateKey: <sshPrivateKey>
  url: git@github.com:CloudNomster/helm-vsphere-csi.git
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-helm-vsphere-cpi
  annotations: 
    avp.kubernetes.io/path: k8s/data/argocd/repositories/argocd-k8s-repo
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  name: Helm Github vSphere CPI
  project: default
  type: git
  sshPrivateKey: <sshPrivateKey>
  url: git@github.com:CloudNomster/helm-vsphere-cpi.git
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-helm-gh-arc-runners
  annotations: 
    avp.kubernetes.io/path: k8s/data/argocd/repositories/argocd-k8s-repo
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  name: Helm Github ARC-runners
  project: default
  type: git
  sshPrivateKey: <sshPrivateKey>
  url: git@github.com:CloudNomster/helm-gh-arc-runners.git
---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-io-repo
  annotations: 
    avp.kubernetes.io/path: k8s/data/github
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  name: ghcr-arc
  project: default
  type: helm
  enableOCI: "true"
  username: schabo
  password: <github_token>
  url: ghcr.io/actions/actions-runner-controller-charts
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-helm-grafana-cloud
  annotations: 
    avp.kubernetes.io/path: k8s/data/argocd/repositories/argocd-k8s-repo
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  name: grafana-cloud
  project: default
  type: helm
  enableOCI: "true"
  username: schabo
  password: <sshPrivateKey>
  url: git@github.com:CloudNomster/helm-grafana-cloud.git