---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-base-repo
  annotations: 
    avp.kubernetes.io/path: k8s/data/argocd/repositories/argocd-k8s-repo
type: Opaque
stringData:
  name: Homelab
  project: default
  type: git
  sshPrivateKey: <sshPrivateKey>
  url: git@github.com:CloudNomster/homelab.git
---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-io-repo
  annotations: 
    avp.kubernetes.io/path: k8s/data/github
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  name: ghcr-arc
  project: default
  type: helm
  enableOCI: "true"
  username: schabo
  password: <github_token>
  url: oci://ghcr.io/actions/actions-runner-controller-charts