---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-base-repo
  annotations: 
    avp.kubernetes.io/path: k8s/data/argocd/repositories/argocd-k8s-repo
type: Opaque
stringData:
  name: Homelab
  project: default
  sshPrivateKey: <sshPrivateKey>
  type: git
  url: git@github.com:CloudNomster/homelab.git
