kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: backstage-read
subjects:
  - kind: ServiceAccount
    name: backstage-read
    namespace: rbac
roleRef:
  kind: ClusterRole
  name: backstage-read
  apiGroup: rbac.authorization.k8s.io
