---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: passwords
  namespace: argocd
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: passwords
    name: in-cluster
  project: default
  source:
    path: k8s/netes/overlays/passwords
    repoURL: git@github.com:CloudNomster/homelab.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - PruneLast=false
      - CreateNamespace=true