---
apiVersion: v1
kind: Secret
metadata:
  name: loki-credentials
  namespace: grafana
type: Opaque
stringData:
  host: <path:k8s/data/grafana#url_loki>
  username: <path:k8s/data/grafana#user_loki>
  password: <path:k8s/data/grafana#token>
