---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-credentials
  namespace: grafana
type: Opaque
stringData:
  host: <path:k8s/data/grafana#url_prometheus>
  username: <path:k8s/data/grafana#user_prometheus>
  password: <path:k8s/data/grafana#token>