---
apiVersion: v1
kind: Secret
metadata:
  name: tempo-credentials
  namespace: grafana
type: Opaque
stringData:
  host: <path:k8s/data/grafana#url_tempo>
  basicAuth:
    username: <path:k8s/data/grafana#user_tempo>
    password: <path:k8s/data/grafana#token>
