---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: vsphere-cpi
  annotations: 
    avp.kubernetes.io/path: k8s/data/vsphere

stringData:
  vsphere.conf: |
    [Global]
    cluster-id = k8s-prod/k8s-prod
    insecure-flag = true
    port = 443
    secretName = csi-vsphere-config
    secretNamespace = kube-system
    [VirtualCenter "<hostname>"]
    datacenters = "GeekHouse"
    password = "<pass>"
    user = <user>
