---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: vsphere-cpi
  annotations: 
    avp.kubernetes.io/path: k8s/data/vsphere

stringData:
  vsphere.conf: |
    vcenter:
    <hostname>:
      datacenters:
        - GeekHouse
      password: <pass>
      server: <hostname>
      user: <user>