---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: github-secrets
  annotations: 
    avp.kubernetes.io/path: k8s/data/github
stringData:
  github_app_id=<github_app_id>
  github_app_installation_id=<github_app_installation_id>
  github_app_private_key=<github_app_private_key>